docs/usage.rst

The small typo is causing bad formatting when converted to HTML.

Fix minor documentation syntax

---

.gitignore

Ignore MANIFEST and .coverage files. These are created during the tox setup.

Ignore MANIFEST and .coverage

---

docs/usage.rst
mailer/engine.py
mailer/tests.py

These extra variables allow tweaking the delivery process to help balance the load of delivery on the server and prevent situations where messages keep getting deferred due to excess requests.
The default values ensure the same behaviour as before.

Allow finer control of message delivery

---

mailer/engine.py
mailer/tests.py

A few logging and deprecation warnings were being printed to the terminal when tests are executing.
This pull request corrects the deprecated code and silences the logging warnings while ensuring they are issued under expected circumstances.

Silence test warnings

---

mailer/models.py

Django 1.8 increases default max_length of EmailField from 75 to 254. Since max_length is not currently specified, but the initial migration contains the 1.8 default of 254, Django 1.7 will think there's a migration to create, decreasing the max_length to 75. This can be fixed by explicitly setting the max_length to 254.

Explicitly set email length to ensure compatibility with Django 1.7

---

.travis.yml
mailer/management/commands/retry_deferred.py
mailer/management/commands/send_mail.py
mailer/management/helpers.py
mailer/tests.py
tox.ini

use argparse for django 1.8+ to avoid deprecation warnings

switch commands to argparse

---

mailer/management/commands/retry_deferred.py
mailer/management/commands/send_mail.py

Fixed Django110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.

Fixed #64 Django110Warning: NoArgsCommand class is deprecated

---

mailer/models.py
mailer/tests.py

I get a 500 error in the mailer message log admin change view without this.
https://docs.djangoproject.com/en/1.8/topics/python3/#str-and-unicode-methods

Add python_2_unicode_compatible decorator to models.

---

.travis.yml
mailer/models.py
tox.ini

django < 2.0 is fine inserting bytestrings into a textfield, but as of 2.0 there is a (py3) `isinstance(str)` -> `str(value)` which for `b'foo'` becomes `"b'foo'"`

django 2.0 compat

---

src/mailer/engine.py

Hi,
I'm using django-mailer with In Django 1.11 and i noticed that the exception caught is only valid for Django 2.0 and up, for 1.11 the exception raised is `DatabaseError` and not `NotSupportedError`.
Documentation: https://docs.djangoproject.com/en/1.11/ref/databases/#row-locking-with-queryset-select-for-update.
This merge fix the problem.

Added django 1.11 compat for nowait exception.

---

src/mailer/migrations/0004_auto_20190920_1512.py

Closes #115.
Changes proposed in this PR:
- Separate the column type change and index creation for MessageLog.priority

Separate the column type change and index creation for MessageLog.priority

---

README.rst

I don't mean to be rude, but
> It works by storing email in the database for later sending.
does absolutely nothing to clarify why some people may run into problems when sending files. It doesn't even make it obvious that file attachments are also stored in the database, or that databases have limits on how big a query they will accept, which by default will be problematic for files any larger than a few KB, which, these days, is probably most files.
Not everyone working on Django knows every little detail about how the database they are using works, or what limits it may or may not have. I know I don't, until I run into issues like this.

Clarified database limitations

---

README.rst
docs/usage.rst
src/mailer/management/commands/purge_mail_log.py
src/mailer/models.py
tests/test_mailer.py

Closes #124.
Changes proposed in this PR:
* added a `-r`/`--result` option to the `purge_mail_log` command in order to remove message logs based on their result code:
* `-r success` (default behaviour for retro-compatibility) to filter logs with `RESULT_SUCCESS` code
* `-r failure` to filter logs with `RESULT_FAILURE` code
* `-r all` to filter logs with either `RESULT_SUCCESS` or `RESULT_FAILURE` codes
* updated the documentation accordingly
I didn't updated the project's version, as I'm not sure you want to publish a new release just for this simple feature.

add option to purge mail logs in failed state

---

CHANGES.rst
docs/usage.rst
src/mailer/engine.py
tests/test_mailer.py

Closes #117
I ran into an issue recently where the send_mail command crashed and the lock file had to be deleted manually.
Since the database locking was added, I'm not really sure why the file-based locking still exists.
This PR adds the `MAILER_USE_FILE_LOCK` setting which defaults to `True` to keep the existing functionality, but it allows disabling the file based locking for users who see it as a liability.

add MAILER_USE_FILE_LOCK setting to disable file locking

---

CHANGES.rst
src/mailer/engine.py

I was looking into why the tests seem slow and found out the tests spend a lot of time calling `socket.getfqdn` from `make_msgid`.
It turns out Django already has a fix for this (since at least 1.11): https://github.com/django/django/blob/stable/1.11.x/django/core/mail/message.py#L327-L328 
This PR applies that same fix Django already uses to cache the calls to `getfqdn`.
Before:
```
10 slowest tests:
35.0928s test_purge_old_entries (tests.test_mailer.SendingTest)
35.0737s test_control_max_retry_amount (tests.test_mailer.SendingTest)
20.0494s test_send_mass_mail (tests.test_mailer.SendingTest)
12.0302s test_throttling_delivery (tests.test_mailer.SendingTest)
10.0393s test_retry_deferred (tests.test_mailer.SendingTest)
10.0254s test_blacklisted_emails (tests.test_mailer.SendingTest) …
```

Use cached DNS_NAME for performance

---

AUTHORS
CHANGES.rst
src/mailer/engine.py
src/mailer/management/commands/purge_mail_log.py
src/mailer/management/commands/retry_deferred.py
src/mailer/management/commands/send_mail.py
src/mailer/management/helpers.py
src/mailer/models.py
tests/test_mailer.py

Currently django-mailer relies on the root logger for logging, but unfortunately this can interfere with other loggers in an application. This can also unintentionally configure the root logger for users who have django configured with `'disable_existing_loggers': True` and potentially cause duplicate log messages.
This PR switches to using module specific loggers with `logger = logging.getLogger(__name__)` to resolve the issue.
This has some other advantages too, like allowing users to adjust log levels for only the django-mailer module.

prevent interference with other logging by not using root logger

---

AUTHORS
CHANGES.rst
README.rst
docs/usage.rst
src/mailer/engine.py
src/mailer/management/commands/runmailer.py

Add the `runmailer` management command that starts the `send_loop` function already available in `mailer.engine`.
Closes #136.

Add runmailer

---

src/mailer/models.py

Make sure Django < 3.2 uses BigAutoField

---

AUTHORS
CHANGES.rst
setup.py
src/mailer/engine.py

Closes: #149 
Error encountered:
```
File "/home/otcomm/otcomm/otcommenv/lib/python3.9/site-packages/mailer/engine.py", line 191, in send_all
", ".join(message.to_addresses))
TypeError: sequence item 1: expected str instance, NoneType found
```
Changes proposed in this PR:
- fix situation where email address is None when submitted from Django view to django-mailer
**Tips for an ideal PR**
* You have read our Code of Conduct: https://github.com/pinax/.github/blob/master/CODE_OF_CONDUCT.md
* You have read our Contributing info: https://github.com/pinax/.github/blob/master/CONTRIBUTING.md
* The PR is atomic
* Unit tests have been updated/added, if needed
* App version number has been updated in `setup.py` (Pinax uses [SemVer](https://semver.org/))
* `Change Log` has been updated
* You have …

fix for expected str instance, NoneType found 

---

.github/workflows/build.yml
CHANGES.rst
tox.ini

As noted in https://github.com/pinax/django-mailer/pull/164#issuecomment-1577436828, support for unsupported versions can be dropped.
This PR removes unsupported versions from the test matrix, and adds recent versions of Django and Python.

Update test matrix

---

AUTHORS
src/mailer/postgres.py

Changes proposed in this PR:
- Add psycopg3 support to runmailer_pg and gracefully exit on SIGINT
**Tips for an ideal PR**
* You have read our Code of Conduct: https://github.com/pinax/.github/blob/master/CODE_OF_CONDUCT.md
* You have read our Contributing info: https://github.com/pinax/.github/blob/master/CONTRIBUTING.md
* The PR is atomic
* Unit tests have been updated/added, if needed
* App version number has been updated in `setup.py` (Pinax uses [SemVer](https://semver.org/))
* `Change Log` has been updated
* You have added your name to the `AUTHORS` file

Add psycopg3 support to runmailer_pg

---

src/mailer/management/commands/send_mail.py

Fix logic for the condition to issue a warning about the deprecated '--cron' argument in the "send_mail" command. The "retry_deferred" command seems to have already the correct check.
P.S.: great package, thank you.

Fix condition for deprecated '--cron' argument in "send_mail" command
